{% set name = "embetter" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/embetter-{{ version }}.tar.gz
  sha256: 6e30fad85b42338c9560d433943462255d01c0a64cace273712acf11721bac8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pandas >=1.0.0
    - python  >=3.7
    - scikit-learn >=1.0.0

test:
  imports:
    - embetter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://koaning.github.io/embetter/
  dev_url: https://github.com/koaning/embetter
  summary: Scikit-learn compatible embeddings for computer vision and text
  license: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - thewchan
