{% set name = "embetter" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/embetter-{{ version }}.tar.gz
  sha256: 2e947474ce3b8f859d04facaa2f0edbd58650071c07a6b0e59482079edb5028f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - scikit-learn >=1.0.0
    - pandas >=1.0.0
    - diskcache >=5.6.1
    - skops >=0.8.0
    - sentence-transformers >=2.2.2
    # For sentence-transformers 3.0.1
    - transformers <5.0.0,>=4.34.0

test:
  imports:
    - embetter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://koaning.github.io/embetter/
  dev_url: https://github.com/koaning/embetter
  summary: Scikit-learn compatible embeddings for computer vision and text
  license: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - thewchan
