{% set name = "embetter" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/embetter-{{ version }}.tar.gz
  sha256: d8af9489cbcd7fd5af75de69d73a49233397adb196c7165c8a12ff85c1739c70

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - diskcache >=5.6.1
    - pandas >=1.0.0
    - python >=3.7
    - scikit-learn >=1.0.0

test:
  imports:
    - embetter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://koaning.github.io/embetter/
  dev_url: https://github.com/koaning/embetter
  summary: Scikit-learn compatible embeddings for computer vision and text
  license: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - thewchan
