{% set name = "embetter" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/embetter-{{ version }}.tar.gz
  sha256: d7070adf2fbaed7f469cf09b08078537598b81418dd88f79f127c65dc1072d4b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pandas >=1.0.0
    - python  >=3.7
    - scikit-learn >=1.0.0

test:
  source_files:
    - tests
  imports:
    - embetter
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k "not test_docs and not test_vision" tests  # [not win]
  requires:
    - mktestdocs==0.1.2
    - pip
    - pillow
    - pytest >=4.0.2
    - sense2vec==2.0.0
    - sentence-transformers >=2.2.2  # [not win]
    - timm >=0.6.7  # [not win]
    - tokenizers!=0.11.3,<0.13,>=0.11.1

about:
  home: https://koaning.github.io/embetter/
  dev_url: https://github.com/koaning/embetter
  summary: Scikit-learn compatible embeddings for computer vision and text
  license: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - thewchan
