{% set name = "embetter" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/embetter-{{ version }}.tar.gz
  sha256: b635e1ca2a13ffb31bff85ba63d02ec6095f37e3f225bf80f6296a83c3a52380

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - scikit-learn >=1.0.0
    - pandas >=1.0.0
    - diskcache >=5.6.1
    - skops >=0.8.0
    - sentence-transformers >=2.2.2
    - model2vec
    # For sentence-transformers 3.0.1
    - transformers <5.0.0,>=4.34.0
    # model2vec has dependency on lightning which pins packaging<25.0,>=17.1
    - packaging <25.0,>=17.1

test:
  imports:
    - embetter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://koaning.github.io/embetter/
  dev_url: https://github.com/koaning/embetter
  summary: Scikit-learn compatible embeddings for computer vision and text
  license: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - thewchan
